# Package imports

In [1]:
import pandas as pd
import pandas_market_calendars as mcal
import numpy as np
from datetime import datetime
import seaborn as sns
import matplotlib.pyplot as plt
import plotly.express as px

import yfinance as yf

# Stock history

In [2]:
events_df = pd.read_csv('data/eps_days.csv')
events_df.head(10)

,date,symbol,when,security_name,exchange_codes,before_eps_date,after_eps_date
0,2023-01-03,LEDS,premarket,SemiLEDS Corporation - Common Stock,NASDAQ,2022-12-30,2023-01-03
1,2023-01-03,SGH,postmarket,"SMART Global Holdings, Inc. - Ordinary Shares",NASDAQ,2023-01-03,2023-01-04
2,2023-01-04,RGP,postmarket,"Resources Connection, Inc. - Common Stock",NASDAQ,2023-01-04,2023-01-05
3,2023-01-04,SLP,postmarket,"Simulations Plus, Inc. - Common Stock",NASDAQ,2023-01-04,2023-01-05
4,2023-01-05,CAG,premarket,"ConAgra Brands, Inc. Common Stock",XNYS,2023-01-04,2023-01-05
5,2023-01-05,HELE,premarket,Helen of Troy Limited - Common Stock,NASDAQ,2023-01-04,2023-01-05
6,2023-01-05,LNN,premarket,Lindsay Corporation Common Stock,XNYS,2023-01-04,2023-01-05
7,2023-01-05,LW,premarket,"Lamb Weston Holdings, Inc. Common Stock",XNYS,2023-01-04,2023-01-05
8,2023-01-05,MSM,premarket,"MSC Industrial Direct Company, Inc. Common Stock",XNYS,2023-01-04,2023-01-05
9,2023-01-05,RPM,premarket,RPM International Inc. Common Stock,XNYS,2023-01-04,2023-01-05

In [3]:
print("DF length:", len(events_df))

DF length: 8456

In [4]:
events_df.dtypes

date               object
symbol             object
when               object
security_name      object
exchange_codes     object
before_eps_date    object
after_eps_date     object
dtype: object

In [5]:
events_df['date'] = pd.to_datetime(events_df['date'])
events_df['after_eps_date'] = pd.to_datetime(events_df['after_eps_date'])
events_df['before_eps_date'] = pd.to_datetime(events_df['before_eps_date'])

In [6]:
unique_tickers = events_df['symbol'].unique().tolist()
print("number of unique tickers:", len(unique_tickers))
print("type:", type(unique_tickers))

number of unique tickers: 2363
type: <class 'list'>

In [7]:
# get smallest before date: 
min_date = events_df['before_eps_date'].min()

print(f'earilest before date : {min_date}')
# get largest after date: 
max_date = events_df['after_eps_date'].max()

print(f'latest after date : {max_date}')

earilest before date : 2022-12-30 00:00:00
latest after date : 2023-12-31 00:00:00

In [52]:
# check tickers 
multi_data = yf.download(unique_tickers, start = '2022-12-30', end = '2023-12-30', interval='1d')
multi_data

[*********************100%%**********************]  2363 of 2363 completed

1 Failed download:
['CVEO']: Exception('%ticker%: No price data found, symbol may be delisted (1d 2022-12-30 -> 2023-12-30)')

Price        Adj Close                                                  \
Ticker               A         AA   AADI    AAN       AAON         AAP
Date
2022-12-30  149.649994  45.470001  12.83  11.95  50.213333  147.029999
2023-01-03  150.039993  44.580002  12.31  11.85  49.886665  151.539993
2023-01-04  151.669998  45.130001  12.67  12.70  47.779999  151.889999
2023-01-05  152.110001  45.490002  12.52  12.75  47.000000  153.160004
2023-01-06  147.669998  46.360001  12.49  13.05  49.459999  154.020004
...                ...        ...    ...    ...        ...         ...
2023-12-22  139.570007  33.770000   1.97  11.11  73.410004   61.250000
2023-12-26  139.809998  33.869999   2.01  11.19  74.150002   60.919998
2023-12-27  139.820007  34.810001   2.08  11.18  74.209999   61.560001
2023-12-28  139.770004  34.549999   2.10  11.17  74.230003   61.490002
2023-12-29  139.029999  34.000000   2.02  10.88  73.870003   61.029999

Price                                                    ...   Volume  \
Ticker            AAT         AB        ABBV       ABCB  ...       ZI
Date                                                     ...
2022-12-30  26.500000  34.369999  161.610001  47.139999  ...  2859400
2023-01-03  26.510000  35.330002  162.380005  46.299999  ...  3246500
2023-01-04  26.959999  35.889999  163.690002  46.490002  ...  8281900
2023-01-05  26.400000  35.520000  163.490005  46.009998  ...  8553500
2023-01-06  27.040001  36.959999  166.550003  47.470001  ...  9252300
...               ...        ...         ...        ...  ...      ...
2023-12-22  22.650000  31.780001  154.940002  52.520000  ...  3096400
2023-12-26  23.040001  31.450001  154.619995  53.580002  ...  2262500
2023-12-27  22.870001  31.330000  154.880005  53.740002  ...  3330600
2023-12-28  22.969999  31.370001  154.750000  53.700001  ...  2348300
2023-12-29  22.510000  31.030001  154.970001  53.049999  ...  2619600

Price                                                                      \
Ticker           ZIM     ZION      ZTO      ZUO    ZVIA     ZVRA      ZWS
Date
2022-12-30   4140200   609700  1205800   869900   94600   301800   890300
2023-01-03   4783800  1175800  1243400  2757500  161000   110100   936700
2023-01-04   2603800  1689000  3024600  1152800   75300   111700  1229800
2023-01-05   3410000   867800  2803200  1251900   41200   103900  1213300
2023-01-06   3160400  1363700  1855300  1054300  239700   181600   568500
...              ...      ...      ...      ...     ...      ...      ...
2023-12-22  11950800  1534500  1735900   604300   92000   219900  1023400
2023-12-26  17195100  1131600  1548900   547600   87400   142500   573500
2023-12-27   7832600  1345100  1606500   922000   64600   619400   987000
2023-12-28   5333900  1125900  3361800   835000  102300  1359000   924500
2023-12-29   5924500  1420600  2938400   855900  106100   895800   754000

Price
Ticker         ZYME     ZYXI
Date
2022-12-30   362500   235600
2023-01-03   716000   182600
2023-01-04   356100    99800
2023-01-05  1022700   122800
2023-01-06   673900  1142500
...             ...      ...
2023-12-22   410700   355200
2023-12-26  1086600   165700
2023-12-27   561000   303500
2023-12-28   477800   364300
2023-12-29   301000   417900

[251 rows x 14178 columns]

In [33]:
multi_data.to_csv('data/stock_price_history.csv', index = False)

In [41]:
# multi_data = pd.read_csv('data/stock_price_history.csv', low_memory = False, header='infer'
#                     )

In [47]:
# test = multi_data.reset_index(drop=False).copy()

In [55]:
multi_data.T.index

MultiIndex([('Adj Close',    'A'),
            ('Adj Close',   'AA'),
            ('Adj Close', 'AADI'),
            ('Adj Close',  'AAN'),
            ('Adj Close', 'AAON'),
            ('Adj Close',  'AAP'),
            ('Adj Close',  'AAT'),
            ('Adj Close',   'AB'),
            ('Adj Close', 'ABBV'),
            ('Adj Close', 'ABCB'),
            ...
            (   'Volume',   'ZI'),
            (   'Volume',  'ZIM'),
            (   'Volume', 'ZION'),
            (   'Volume',  'ZTO'),
            (   'Volume',  'ZUO'),
            (   'Volume', 'ZVIA'),
            (   'Volume', 'ZVRA'),
            (   'Volume',  'ZWS'),
            (   'Volume', 'ZYME'),
            (   'Volume', 'ZYXI')],
           names=['Price', 'Ticker'], length=14178)

In [56]:
multi_data.columns = multi_data.columns.map('_'.join)

In [59]:
multi_data = multi_data.T.reset_index().copy()
multi_data

Date,index,2022-12-30 00:00:00,2023-01-03 00:00:00,2023-01-04 00:00:00,2023-01-05 00:00:00,2023-01-06 00:00:00,2023-01-09 00:00:00,2023-01-10 00:00:00,2023-01-11 00:00:00,2023-01-12 00:00:00,...,2023-12-15 00:00:00,2023-12-18 00:00:00,2023-12-19 00:00:00,2023-12-20 00:00:00,2023-12-21 00:00:00,2023-12-22 00:00:00,2023-12-26 00:00:00,2023-12-27 00:00:00,2023-12-28 00:00:00,2023-12-29 00:00:00
0,Adj Close_A,149.649994,150.039993,1.516700e+02,1.521100e+02,1.476700e+02,147.470001,1.552300e+02,1.581700e+02,1.564900e+02,...,1.367800e+02,1.375300e+02,1.397900e+02,1.381800e+02,138.940002,1.395700e+02,1.398100e+02,139.820007,1.397700e+02,139.029999
1,Adj Close_AA,45.470001,44.580002,4.513000e+01,4.549000e+01,4.636000e+01,50.270000,5.298000e+01,5.195000e+01,5.332000e+01,...,3.110000e+01,3.052000e+01,3.242000e+01,3.065000e+01,32.020000,3.377000e+01,3.387000e+01,34.810001,3.455000e+01,34.000000
2,Adj Close_AADI,12.830000,12.310000,1.267000e+01,1.252000e+01,1.249000e+01,12.130000,1.230000e+01,1.229000e+01,1.300000e+01,...,2.340000e+00,2.240000e+00,2.210000e+00,2.060000e+00,1.990000,1.970000e+00,2.010000e+00,2.080000,2.100000e+00,2.020000
3,Adj Close_AAN,11.950000,11.850000,1.270000e+01,1.275000e+01,1.305000e+01,13.280000,1.346000e+01,1.416000e+01,1.431000e+01,...,1.109000e+01,1.097000e+01,1.119000e+01,1.089000e+01,11.170000,1.111000e+01,1.119000e+01,11.180000,1.117000e+01,10.880000
4,Adj Close_AAON,50.213333,49.886665,4.778000e+01,4.700000e+01,4.946000e+01,49.606667,5.040667e+01,5.064667e+01,5.116000e+01,...,7.111000e+01,7.074000e+01,7.236000e+01,7.178000e+01,72.389999,7.341000e+01,7.415000e+01,74.209999,7.423000e+01,73.870003
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14173,Volume_ZVIA,94600.000000,161000.000000,7.530000e+04,4.120000e+04,2.397000e+05,93700.000000,6.710000e+04,5.400000e+04,9.730000e+04,...,1.978000e+05,9.720000e+04,2.005000e+05,1.577000e+05,103700.000000,9.200000e+04,8.740000e+04,64600.000000,1.023000e+05,106100.000000
14174,Volume_ZVRA,301800.000000,110100.000000,1.117000e+05,1.039000e+05,1.816000e+05,238100.000000,2.034000e+05,2.508000e+05,3.668000e+05,...,4.757000e+05,2.208000e+05,2.123000e+05,2.154000e+05,141000.000000,2.199000e+05,1.425000e+05,619400.000000,1.359000e+06,895800.000000
14175,Volume_ZWS,890300.000000,936700.000000,1.229800e+06,1.213300e+06,5.685000e+05,580200.000000,6.355000e+05,6.147000e+05,1.011800e+06,...,2.160300e+06,1.210000e+06,1.260900e+06,1.253300e+06,671300.000000,1.023400e+06,5.735000e+05,987000.000000,9.245000e+05,754000.000000
14176,Volume_ZYME,362500.000000,716000.000000,3.561000e+05,1.022700e+06,6.739000e+05,567800.000000,2.276400e+06,1.505900e+06,5.013000e+05,...,1.142200e+06,5.713000e+05,3.588000e+05,3.556000e+05,268300.000000,4.107000e+05,1.086600e+06,561000.000000,4.778000e+05,301000.000000
14177,Volume_ZYXI,235600.000000,182600.000000,9.980000e+04,1.228000e+05,1.142500e+06,333600.000000,5.037000e+05,3.105000e+05,1.671000e+05,...,5.453000e+05,3.162000e+05,3.148000e+05,2.220000e+05,847100.000000,3.552000e+05,1.657000e+05,303500.000000,3.643000e+05,417900.000000

In [60]:
# Split the 'Column' into two columns
multi_data[['Status', 'Ticker']] = multi_data['index'].str.split('_', expand=True)

In [62]:
multi_data = multi_data.drop(columns = 'index')
multi_data

Date,2022-12-30 00:00:00,2023-01-03 00:00:00,2023-01-04 00:00:00,2023-01-05 00:00:00,2023-01-06 00:00:00,2023-01-09 00:00:00,2023-01-10 00:00:00,2023-01-11 00:00:00,2023-01-12 00:00:00,2023-01-13 00:00:00,...,2023-12-19 00:00:00,2023-12-20 00:00:00,2023-12-21 00:00:00,2023-12-22 00:00:00,2023-12-26 00:00:00,2023-12-27 00:00:00,2023-12-28 00:00:00,2023-12-29 00:00:00,Status,Ticker
0,149.649994,150.039993,1.516700e+02,1.521100e+02,1.476700e+02,147.470001,1.552300e+02,1.581700e+02,1.564900e+02,1.569200e+02,...,1.397900e+02,1.381800e+02,138.940002,1.395700e+02,1.398100e+02,139.820007,1.397700e+02,139.029999,Adj Close,A
1,45.470001,44.580002,4.513000e+01,4.549000e+01,4.636000e+01,50.270000,5.298000e+01,5.195000e+01,5.332000e+01,5.461000e+01,...,3.242000e+01,3.065000e+01,32.020000,3.377000e+01,3.387000e+01,34.810001,3.455000e+01,34.000000,Adj Close,AA
2,12.830000,12.310000,1.267000e+01,1.252000e+01,1.249000e+01,12.130000,1.230000e+01,1.229000e+01,1.300000e+01,1.295000e+01,...,2.210000e+00,2.060000e+00,1.990000,1.970000e+00,2.010000e+00,2.080000,2.100000e+00,2.020000,Adj Close,AADI
3,11.950000,11.850000,1.270000e+01,1.275000e+01,1.305000e+01,13.280000,1.346000e+01,1.416000e+01,1.431000e+01,1.435000e+01,...,1.119000e+01,1.089000e+01,11.170000,1.111000e+01,1.119000e+01,11.180000,1.117000e+01,10.880000,Adj Close,AAN
4,50.213333,49.886665,4.778000e+01,4.700000e+01,4.946000e+01,49.606667,5.040667e+01,5.064667e+01,5.116000e+01,5.191333e+01,...,7.236000e+01,7.178000e+01,72.389999,7.341000e+01,7.415000e+01,74.209999,7.423000e+01,73.870003,Adj Close,AAON
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14173,94600.000000,161000.000000,7.530000e+04,4.120000e+04,2.397000e+05,93700.000000,6.710000e+04,5.400000e+04,9.730000e+04,4.510000e+04,...,2.005000e+05,1.577000e+05,103700.000000,9.200000e+04,8.740000e+04,64600.000000,1.023000e+05,106100.000000,Volume,ZVIA
14174,301800.000000,110100.000000,1.117000e+05,1.039000e+05,1.816000e+05,238100.000000,2.034000e+05,2.508000e+05,3.668000e+05,2.643000e+05,...,2.123000e+05,2.154000e+05,141000.000000,2.199000e+05,1.425000e+05,619400.000000,1.359000e+06,895800.000000,Volume,ZVRA
14175,890300.000000,936700.000000,1.229800e+06,1.213300e+06,5.685000e+05,580200.000000,6.355000e+05,6.147000e+05,1.011800e+06,9.679000e+05,...,1.260900e+06,1.253300e+06,671300.000000,1.023400e+06,5.735000e+05,987000.000000,9.245000e+05,754000.000000,Volume,ZWS
14176,362500.000000,716000.000000,3.561000e+05,1.022700e+06,6.739000e+05,567800.000000,2.276400e+06,1.505900e+06,5.013000e+05,1.641900e+06,...,3.588000e+05,3.556000e+05,268300.000000,4.107000e+05,1.086600e+06,561000.000000,4.778000e+05,301000.000000,Volume,ZYME
14177,235600.000000,182600.000000,9.980000e+04,1.228000e+05,1.142500e+06,333600.000000,5.037000e+05,3.105000e+05,1.671000e+05,1.622000e+05,...,3.148000e+05,2.220000e+05,847100.000000,3.552000e+05,1.657000e+05,303500.000000,3.643000e+05,417900.000000,Volume,ZYXI

In [64]:
multi_data = multi_data.melt(id_vars=['Status', 'Ticker'])

In [68]:
multi_data = multi_data.rename_axis('Index')
multi_data

            Status Ticker                 Date          value
Index
0        Adj Close      A  2022-12-30 00:00:00     149.649994
1        Adj Close     AA  2022-12-30 00:00:00      45.470001
2        Adj Close   AADI  2022-12-30 00:00:00      12.830000
3        Adj Close    AAN  2022-12-30 00:00:00      11.950000
4        Adj Close   AAON  2022-12-30 00:00:00      50.213333
...            ...    ...                  ...            ...
3558673     Volume   ZVIA  2023-12-29 00:00:00  106100.000000
3558674     Volume   ZVRA  2023-12-29 00:00:00  895800.000000
3558675     Volume    ZWS  2023-12-29 00:00:00  754000.000000
3558676     Volume   ZYME  2023-12-29 00:00:00  301000.000000
3558677     Volume   ZYXI  2023-12-29 00:00:00  417900.000000

[3558678 rows x 4 columns]

In [73]:
multi_data

            Status Ticker                 Date          value
Index
0        Adj Close      A  2022-12-30 00:00:00     149.649994
1        Adj Close     AA  2022-12-30 00:00:00      45.470001
2        Adj Close   AADI  2022-12-30 00:00:00      12.830000
3        Adj Close    AAN  2022-12-30 00:00:00      11.950000
4        Adj Close   AAON  2022-12-30 00:00:00      50.213333
...            ...    ...                  ...            ...
3558673     Volume   ZVIA  2023-12-29 00:00:00  106100.000000
3558674     Volume   ZVRA  2023-12-29 00:00:00  895800.000000
3558675     Volume    ZWS  2023-12-29 00:00:00  754000.000000
3558676     Volume   ZYME  2023-12-29 00:00:00  301000.000000
3558677     Volume   ZYXI  2023-12-29 00:00:00  417900.000000

[3558678 rows x 4 columns]

In [84]:
clean_df = multi_data.pivot(index = ['Ticker', 'Date'], columns='Status', values='value').copy()
clean_df = clean_df.reset_index()

In [89]:
clean_df.to_csv('data/stock_price_history_clean.csv', index = False)

In [90]:
prices_df = pd.read_csv('data/stock_price_history_clean.csv')
prices_df

,Ticker,Date,Adj Close,Close,High,Low,Open,Volume
0,A,2022-12-30,149.649994,149.649994,149.850006,147.830002,149.759995,699800.0
1,A,2023-01-03,150.039993,150.039993,153.130005,148.470001,151.960007,1414300.0
2,A,2023-01-04,151.669998,151.669998,153.039993,150.240005,151.649994,1247400.0
3,A,2023-01-05,152.110001,152.110001,153.070007,148.770004,150.000000,1714600.0
4,A,2023-01-06,147.669998,147.669998,154.639999,143.009995,154.360001,2445000.0
...,...,...,...,...,...,...,...,...
593108,ZYXI,2023-12-22,10.640000,10.640000,10.740000,10.400000,10.650000,355200.0
593109,ZYXI,2023-12-26,10.710000,10.710000,10.850000,10.610000,10.640000,165700.0
593110,ZYXI,2023-12-27,10.770000,10.770000,11.030000,10.700000,10.700000,303500.0
593111,ZYXI,2023-12-28,10.890000,10.890000,10.950000,10.720000,10.730000,364300.0
593112,ZYXI,2023-12-29,10.890000,10.890000,10.970000,10.720000,10.880000,417900.0

In [91]:
prices_df.sort_values(by = ['Ticker', 'Date'], ascending = True)

,Ticker,Date,Adj Close,Close,High,Low,Open,Volume
0,A,2022-12-30,149.649994,149.649994,149.850006,147.830002,149.759995,699800.0
1,A,2023-01-03,150.039993,150.039993,153.130005,148.470001,151.960007,1414300.0
2,A,2023-01-04,151.669998,151.669998,153.039993,150.240005,151.649994,1247400.0
3,A,2023-01-05,152.110001,152.110001,153.070007,148.770004,150.000000,1714600.0
4,A,2023-01-06,147.669998,147.669998,154.639999,143.009995,154.360001,2445000.0
...,...,...,...,...,...,...,...,...
593108,ZYXI,2023-12-22,10.640000,10.640000,10.740000,10.400000,10.650000,355200.0
593109,ZYXI,2023-12-26,10.710000,10.710000,10.850000,10.610000,10.640000,165700.0
593110,ZYXI,2023-12-27,10.770000,10.770000,11.030000,10.700000,10.700000,303500.0
593111,ZYXI,2023-12-28,10.890000,10.890000,10.950000,10.720000,10.730000,364300.0
593112,ZYXI,2023-12-29,10.890000,10.890000,10.970000,10.720000,10.880000,417900.0

In [12]:
stock_status = []
for num in range(len(cols)):
        stock_status.append(cols[num][0])

In [13]:
stock_status_list = list(set(stock_status))
stock_status_list

['High', 'Volume', 'Close', 'Low', 'Adj Close', 'Open']

In [12]:
stock_result = pd.DataFrame()
def stock_history(row):
    ''' get stock prices for the days between before and after for each stock'''
    ticker = row['symbol']
    # print(ticker)
    data = yf.Ticker(ticker)
    result = data.history(start=row['before_eps_date'], end = row['after_eps_date']+pd.Timedelta(days=1))
    result['symbol'] = ticker
    result.reset_index(drop=False, inplace=True)
    result.set_index('symbol', inplace =True)
    # result['Date'] = pd.to_datetime(result['Date'])
    result['Date'] = pd.to_datetime(result['Date']).dt.strftime('%Y-%m-%d')
    return result

In [13]:
# QA testing one row
# pct_test = stock_history(events_df.iloc[1,:])

# pct_test

# full DF
prices = events_df.apply(stock_history, axis=1)
prices

CR: Data doesn't exist for startDate = 1674450000, endDate = 1674622800
DBD: Data doesn't exist for startDate = 1675832400, endDate = 1676005200
MSGE: Data doesn't exist for startDate = 1675832400, endDate = 1676005200

KeyboardInterrupt:

In [ ]:
pct_test.dtypes

In [ ]:

pct_test = pct_test[['Open', 'High','Low','Close']].pct_change(axis=0).dropna()

In [ ]:
pct_test

In [ ]:
pct_test = pct_test[['Open', 'High','Low','Close']].pct_change(axis=0).dropna()

## Bin

In [ ]:
ticker_list = events_df['symbol'].tolist()
ticker_list = set([ticker.lower() for ticker in ticker_list])
print(len(ticker_list))
ticker_list

In [ ]:
print(events_df.loc[0,'after_eps_date'])
print(events_df.loc[0,'after_eps_date']+pd.Timedelta(days=1))

In [ ]:
events_df['after_eps_date'] = np.nan
events_df['before_eps_date'] = np.nan

In [ ]:
events_df

In [ ]:
### next trading day is after eps date for all values where WHEN = Postmarket

# Define a function to conditionally replace values
def get_after_date(row):
    if row['when'] == 'postmarket':
        return row['next_trading_day']
    elif row['when'] == 'premarket':
        return row['date']
    else:
        return row['next_trading_day']

# Apply the function to create a new column 'D' with the replaced values
events_df['after_eps_date'] = events_df.apply(get_after_date, axis=1)

In [ ]:
events_df

In [ ]:
# Define a function to conditionally replace values
def get_before_date(row):
    if row['when'] == 'postmarket':
        return row['date']
    elif row['when'] == 'premarket':
        return row['prior_trading_day']
    else:
        return row['next_trading_day']

# Apply the function to create a new column 'D' with the replaced values
events_df['before_eps_date'] = events_df.apply(get_before_date, axis=1)

In [ ]:


events_df.dtypes

In [ ]:
events_df['after_eps_date'] = pd.to_datetime(events_df['after_eps_date'])
events_df['before_eps_date'] = pd.to_datetime(events_df['before_eps_date'])

In [ ]:
events_df.head(15)

In [ ]:
events_df.dtypes