# Document Purpose:
* purpose of this notebook is to merge the stock price data on particular earnings announcement dates with the EPS data for those dates into one dataframe

# Imports

In [1]:
import pandas as pd
import numpy as np

# Cleaning

In [2]:
events_df = pd.read_csv("data/exports/stock_price_pct_change_history.csv")
# drop unecessary columns
events_df = events_df[['date', 'symbol','security_name', 'when',
       'before_eps_date', 'after_eps_date', 'Adj Close',
       'Close',  'Adj Close_pct_change',
       'Close_pct_change']].copy()

In [3]:
eps_data = pd.read_csv("data/exports/eps_data.csv")

In [4]:
eps_data

,Earnings Date,EPS Estimate,Reported EPS,Surprise(%),Symbol
0,2025-01-02 07:00:00-05:00,NaN,NaN,NaN,CAG
1,2024-10-03 08:00:00-04:00,NaN,NaN,NaN,CAG
2,2024-07-11 08:00:00-04:00,NaN,NaN,NaN,CAG
3,2024-04-04 09:00:00-04:00,0.64,NaN,NaN,CAG
4,2024-04-04 08:00:00-04:00,0.64,NaN,NaN,CAG
...,...,...,...,...,...
21536,2020-08-04 16:00:00-04:00,0.13,0.27,1.0301,MNR
21537,2020-05-06 16:00:00-04:00,0.09,-0.77,-9.2796,MNR
21538,2020-02-06 16:00:00-05:00,0.11,0.04,-0.6190,MNR
21539,2019-11-25 16:00:00-05:00,0.10,0.24,1.5263,MNR
21540,2019-08-01 16:00:00-04:00,0.10,-0.03,-1.3158,MNR

In [5]:
events_df[events_df["symbol"] == "SGH"]
# events_df.head()

,date,symbol,security_name,when,before_eps_date,after_eps_date,Adj Close,Close,Adj Close_pct_change,Close_pct_change
1,2023-01-03,SGH,"SMART Global Holdings, Inc. - Ordinary Shares",postmarket,2023-01-03,2023-01-04,15.75,15.75,0.041667,0.041667
4188,2023-06-29,SGH,"SMART Global Holdings, Inc. - Ordinary Shares",postmarket,2023-06-29,2023-06-30,29.01,29.01,0.089373,0.089373
6370,2023-10-12,SGH,"SMART Global Holdings, Inc. - Ordinary Shares",postmarket,2023-10-12,2023-10-13,13.10,13.10,-0.444444,-0.444444

In [6]:
eps_data[eps_data["Symbol"] == "SGH"]

Empty DataFrame
Columns: [Earnings Date, EPS Estimate, Reported EPS, Surprise(%), Symbol]
Index: []

In [7]:
#how many rows where reported EPS is NaN: ~= 7803 rows
eps_data[eps_data[[ "Reported EPS"]].isna().all(axis=1)]

,Earnings Date,EPS Estimate,Reported EPS,Surprise(%),Symbol
0,2025-01-02 07:00:00-05:00,NaN,NaN,NaN,CAG
1,2024-10-03 08:00:00-04:00,NaN,NaN,NaN,CAG
2,2024-07-11 08:00:00-04:00,NaN,NaN,NaN,CAG
3,2024-04-04 09:00:00-04:00,0.64,NaN,NaN,CAG
4,2024-04-04 08:00:00-04:00,0.64,NaN,NaN,CAG
...,...,...,...,...,...
21517,2025-02-26 16:00:00-05:00,NaN,NaN,NaN,SDRL
21518,2024-11-25 05:00:00-05:00,NaN,NaN,NaN,SDRL
21519,2024-08-13 14:00:00-04:00,NaN,NaN,NaN,SDRL
21520,2024-05-21 08:00:00-04:00,0.68,NaN,NaN,SDRL
21528,2022-05-25 07:00:00-04:00,NaN,NaN,NaN,SDRL

In [8]:
# drop rows where reported EPS is NaN:
eps_data = eps_data.dropna(axis = 0, subset= ["Reported EPS"], ignore_index = True).copy()
eps_data

,Earnings Date,EPS Estimate,Reported EPS,Surprise(%),Symbol
0,2024-01-04 07:00:00-05:00,0.68,0.71,0.0451,CAG
1,2023-10-05 07:00:00-04:00,0.60,0.66,0.1038,CAG
2,2023-07-13 07:00:00-04:00,0.59,0.62,0.0467,CAG
3,2023-04-05 07:00:00-04:00,0.64,0.76,0.1883,CAG
4,2023-01-05 07:00:00-05:00,0.66,0.81,0.2193,CAG
...,...,...,...,...,...
13969,2020-08-04 16:00:00-04:00,0.13,0.27,1.0301,MNR
13970,2020-05-06 16:00:00-04:00,0.09,-0.77,-9.2796,MNR
13971,2020-02-06 16:00:00-05:00,0.11,0.04,-0.6190,MNR
13972,2019-11-25 16:00:00-05:00,0.10,0.24,1.5263,MNR
13973,2019-08-01 16:00:00-04:00,0.10,-0.03,-1.3158,MNR

In [9]:
eps_data[eps_data[['EPS Estimate', "Reported EPS", "Surprise(%)"]].isna().any(axis=1)]

,Earnings Date,EPS Estimate,Reported EPS,Surprise(%),Symbol
92,2022-11-28 20:00:00-05:00,-0.02,-0.02,NaN,OGI
135,2023-04-27 06:00:00-04:00,0.07,0.07,NaN,WIT
136,2023-01-13 05:00:00-05:00,0.07,0.07,NaN,WIT
141,2021-10-13 06:00:00-04:00,0.07,0.07,NaN,WIT
302,2022-03-11 16:00:00-05:00,NaN,0.05,NaN,FPH
...,...,...,...,...,...
13911,2022-08-11 16:00:00-04:00,-0.41,-0.41,NaN,NVVE
13920,2022-11-02 16:00:00-04:00,0.02,0.02,NaN,PFIE
13933,2023-11-14 07:00:00-05:00,NaN,-0.03,NaN,ISPR
13947,2023-08-14 16:00:00-04:00,NaN,0.01,NaN,POL
13963,2022-02-04 16:00:00-05:00,NaN,0.12,NaN,MNR

In [10]:
eps_data.dtypes

Earnings Date     object
EPS Estimate     float64
Reported EPS     float64
Surprise(%)      float64
Symbol            object
dtype: object

In [11]:
# Convert 'date' column to datetime type
eps_data["Earnings Date"] = pd.to_datetime(eps_data["Earnings Date"], utc=True).dt.strftime('%Y-%m-%d')
print(eps_data.dtypes)

Earnings Date     object
EPS Estimate     float64
Reported EPS     float64
Surprise(%)      float64
Symbol            object
dtype: object

In [12]:
events_df.dtypes

date                     object
symbol                   object
security_name            object
when                     object
before_eps_date          object
after_eps_date           object
Adj Close               float64
Close                   float64
Adj Close_pct_change    float64
Close_pct_change        float64
dtype: object

# Merge EPS Data, Stock Data Pct Changes

Merge based on date and stock

In [13]:
events_df.sort_values(by = ["symbol", 'date'])

,date,symbol,security_name,when,before_eps_date,after_eps_date,Adj Close,Close,Adj Close_pct_change,Close_pct_change
1401,2023-02-28,A,"Agilent Technologies, Inc. Common Stock",postmarket,2023-02-28,2023-03-01,137.509995,137.509995,-0.031415,-0.031415
3975,2023-05-23,A,"Agilent Technologies, Inc. Common Stock",postmarket,2023-05-23,2023-05-24,120.989998,120.989998,-0.059468,-0.059468
6088,2023-08-15,A,"Agilent Technologies, Inc. Common Stock",postmarket,2023-08-15,2023-08-16,121.360001,121.360001,-0.034142,-0.034142
8298,2023-11-20,A,"Agilent Technologies, Inc. Common Stock",postmarket,2023-11-20,2023-11-21,123.919998,123.919998,0.087208,0.087208
36,2023-01-18,AA,Alcoa Corporation Common Stock,postmarket,2023-01-18,2023-01-19,49.520000,49.520000,-0.073527,-0.073527
...,...,...,...,...,...,...,...,...,...,...
3419,2023-05-08,ZYME,Zymeworks Inc. - Common Stock,postmarket,2023-05-08,2023-05-09,9.880000,9.880000,0.127854,0.127854
1821,2023-03-13,ZYXI,"Zynex, Inc. - Common Stock",premarket,2023-03-10,2023-03-13,10.940000,10.940000,0.147954,0.147954
2590,2023-04-27,ZYXI,"Zynex, Inc. - Common Stock",premarket,2023-04-26,2023-04-27,11.270000,11.270000,0.009857,0.009857
4727,2023-07-27,ZYXI,"Zynex, Inc. - Common Stock",premarket,2023-07-26,2023-07-27,9.750000,9.750000,0.018809,0.018809
6859,2023-10-26,ZYXI,"Zynex, Inc. - Common Stock",premarket,2023-10-25,2023-10-26,7.150000,7.150000,0.007042,0.007042

In [14]:
eps_data.sort_values(by = ["Symbol", 'Earnings Date'])

      Earnings Date  EPS Estimate  Reported EPS  Surprise(%) Symbol
229      2022-04-20          2.93          3.06       0.0428     AA
228      2022-07-20          2.31          2.67       0.1538     AA
227      2022-10-19          0.19         -0.33      -2.7314     AA
226      2023-01-18         -0.92         -0.70       0.2375     AA
225      2023-04-19         -0.11         -0.23      -1.1766     AA
...             ...           ...           ...          ...    ...
11043    2023-03-13          0.19          0.20       0.0601   ZYXI
11042    2023-04-27          0.01          0.04       2.0008   ZYXI
11041    2023-07-27          0.05          0.09       1.0000   ZYXI
11040    2023-10-26          0.09          0.10       0.0715   ZYXI
11039    2024-02-29          0.17          0.21       0.2353   ZYXI

[13974 rows x 5 columns]

#### Decision: 
for earnings events where there is no matching earnings values, these event dates will be dropped.
The ML model requires complete data.

In [15]:
merged_df = events_df.merge(eps_data, left_on = ['date', 'symbol'], right_on = ["Earnings Date", "Symbol"], how = "inner")
merged_df

,date,symbol,security_name,when,before_eps_date,after_eps_date,Adj Close,Close,Adj Close_pct_change,Close_pct_change,Earnings Date,EPS Estimate,Reported EPS,Surprise(%),Symbol
0,2023-01-05,CAG,"ConAgra Brands, Inc. Common Stock",premarket,2023-01-04,2023-01-05,39.970001,39.970001,0.034153,0.034153,2023-01-05,0.66,0.81,0.2193,CAG
1,2023-01-05,HELE,Helen of Troy Limited - Common Stock,premarket,2023-01-04,2023-01-05,110.970001,110.970001,-0.014301,-0.014301,2023-01-05,2.61,2.75,0.0551,HELE
2,2023-01-05,LNN,Lindsay Corporation Common Stock,premarket,2023-01-04,2023-01-05,161.860001,161.860001,0.033325,0.033325,2023-01-05,1.18,1.65,0.3983,LNN
3,2023-01-05,LW,"Lamb Weston Holdings, Inc. Common Stock",premarket,2023-01-04,2023-01-05,96.029999,96.029999,0.097737,0.097737,2023-01-05,0.74,1.28,0.7231,LW
4,2023-01-05,MSM,"MSC Industrial Direct Company, Inc. Common Stock",premarket,2023-01-04,2023-01-05,77.029999,77.029999,-0.054847,-0.054847,2023-01-05,1.46,1.48,0.0126,MSM
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5929,2023-12-21,CCL,Carnival Corporation Common Stock,premarket,2023-12-20,2023-12-21,19.190001,19.190001,0.061981,0.061981,2023-12-21,-0.13,-0.07,0.4615,CCL
5930,2023-12-21,KMX,CarMax Inc,premarket,2023-12-20,2023-12-21,78.550003,78.550003,0.051821,0.051821,2023-12-21,0.43,0.52,0.2178,KMX
5931,2023-12-21,LMNR,Limoneira Co - Common Stock,postmarket,2023-12-21,2023-12-22,20.510000,20.510000,0.068786,0.068786,2023-12-21,-0.15,-0.15,0.0196,LMNR
5932,2023-12-21,NKE,"Nike, Inc. Common Stock",premarket,2023-12-20,2023-12-21,122.529999,122.529999,0.009059,0.009059,2023-12-21,0.85,1.03,0.2175,NKE
5933,2023-12-21,PAYX,"Paychex, Inc. - Common Stock",premarket,2023-12-20,2023-12-21,118.900002,118.900002,-0.070077,-0.070077,2023-12-21,1.07,1.08,0.0056,PAYX

 ### QA:
 confirming merge performed as expected by doing a full outer merge first, then reviewing results for individual stocks. 

 Result = if no earnings date is associated with the "date" field, ok to drop row,

In [16]:
merged_df[merged_df['Earnings Date'].isnull()]

Empty DataFrame
Columns: [date, symbol, security_name, when, before_eps_date, after_eps_date, Adj Close, Close, Adj Close_pct_change, Close_pct_change, Earnings Date, EPS Estimate, Reported EPS, Surprise(%), Symbol]
Index: []

In [17]:
stock = "OGI"
single_stock_df = merged_df[(merged_df['symbol'] == stock) | (merged_df['Symbol'] == stock)]
single_stock_df

,date,symbol,security_name,when,before_eps_date,after_eps_date,Adj Close,Close,Adj Close_pct_change,Close_pct_change,Earnings Date,EPS Estimate,Reported EPS,Surprise(%),Symbol
1441,2023-04-11,OGI,Organigram Holdings Inc. - Common Shares,postmarket,2023-04-11,2023-04-12,2.40,2.40,-0.124088,-0.124088,2023-04-11,-0.02,-0.02,-0.200,OGI
5924,2023-12-19,OGI,Organigram Holdings Inc. - Common Shares,premarket,2023-12-18,2023-12-19,1.27,1.27,-0.030534,-0.030534,2023-12-19,-0.14,-0.13,0.073,OGI

In [18]:
merged_df.sort_values(by=['symbol', 'Symbol', 'date', "Earnings Date"], na_position = 'last').head(2000)

,date,symbol,security_name,when,before_eps_date,after_eps_date,Adj Close,Close,Adj Close_pct_change,Close_pct_change,Earnings Date,EPS Estimate,Reported EPS,Surprise(%),Symbol
25,2023-01-18,AA,Alcoa Corporation Common Stock,postmarket,2023-01-18,2023-01-19,49.520000,49.520000,-0.073527,-0.073527,2023-01-18,-0.92,-0.70,0.2375,AA
1463,2023-04-19,AA,Alcoa Corporation Common Stock,postmarket,2023-04-19,2023-04-20,40.230000,40.230000,-0.024018,-0.024018,2023-04-19,-0.11,-0.23,-1.1766,AA
2964,2023-07-19,AA,Alcoa Corporation Common Stock,postmarket,2023-07-19,2023-07-20,32.680000,32.680000,-0.061998,-0.061998,2023-07-19,-0.52,-0.35,0.3214,AA
4480,2023-10-18,AA,Alcoa Corporation Common Stock,postmarket,2023-10-18,2023-10-19,24.240000,24.240000,-0.085973,-0.085973,2023-10-18,-1.02,-1.14,-0.1166,AA
1069,2023-03-01,AAN,"Aarons Holdings Company, Inc. Common Stock",postmarket,2023-03-01,2023-03-02,12.370000,12.370000,-0.140972,-0.140972,2023-03-01,0.01,0.09,5.9984,AAN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
881,2023-02-23,EIX,Edison International Common Stock,premarket,2023-02-22,2023-02-23,65.860001,65.860001,-0.005136,-0.005136,2023-02-23,1.10,1.15,0.0454,EIX
1929,2023-05-02,EIX,Edison International Common Stock,premarket,2023-05-01,2023-05-02,73.279999,73.279999,-0.009060,-0.009060,2023-05-02,0.96,1.09,0.1412,EIX
3238,2023-07-27,EIX,Edison International Common Stock,premarket,2023-07-26,2023-07-27,70.860001,70.860001,-0.017198,-0.017198,2023-07-27,0.96,1.01,0.0564,EIX
736,2023-02-21,ELAN,Elanco Animal Health Incorporated Common Stock,premarket,2023-02-17,2023-02-21,11.620000,11.620000,-0.115004,-0.115004,2023-02-21,0.13,0.19,0.4809,ELAN
2470,2023-05-09,ELAN,Elanco Animal Health Incorporated Common Stock,premarket,2023-05-08,2023-05-09,9.310000,9.310000,-0.005342,-0.005342,2023-05-09,0.29,0.45,0.5607,ELAN

In [19]:
merged_df.columns

Index(['date', 'symbol', 'security_name', 'when', 'before_eps_date',
       'after_eps_date', 'Adj Close', 'Close', 'Adj Close_pct_change',
       'Close_pct_change', 'Earnings Date', 'EPS Estimate', 'Reported EPS',
       'Surprise(%)', 'Symbol'],
      dtype='object')

In [20]:
# drop duplicate columns
merged_df.drop(columns =[ 'Earnings Date','Symbol'], inplace = True)

In [26]:
# convert when to binary 
merged_df.loc[merged_df['when'] == 'premarket','when'] = 1
merged_df.loc[merged_df['when'] == 'postmarket','when'] = 0
merged_df = merged_df.rename(columns = {'when': 'premarket_pub'}).copy()
merged_df

,date,symbol,security_name,premarket_pub,before_eps_date,after_eps_date,Adj Close,Close,Adj Close_pct_change,Close_pct_change,EPS Estimate,Reported EPS,Surprise(%),premarket
0,2023-01-05,CAG,"ConAgra Brands, Inc. Common Stock",1,2023-01-04,2023-01-05,39.970001,39.970001,0.034153,0.034153,0.66,0.81,0.2193,1.0
1,2023-01-05,HELE,Helen of Troy Limited - Common Stock,1,2023-01-04,2023-01-05,110.970001,110.970001,-0.014301,-0.014301,2.61,2.75,0.0551,1.0
2,2023-01-05,LNN,Lindsay Corporation Common Stock,1,2023-01-04,2023-01-05,161.860001,161.860001,0.033325,0.033325,1.18,1.65,0.3983,1.0
3,2023-01-05,LW,"Lamb Weston Holdings, Inc. Common Stock",1,2023-01-04,2023-01-05,96.029999,96.029999,0.097737,0.097737,0.74,1.28,0.7231,1.0
4,2023-01-05,MSM,"MSC Industrial Direct Company, Inc. Common Stock",1,2023-01-04,2023-01-05,77.029999,77.029999,-0.054847,-0.054847,1.46,1.48,0.0126,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5929,2023-12-21,CCL,Carnival Corporation Common Stock,1,2023-12-20,2023-12-21,19.190001,19.190001,0.061981,0.061981,-0.13,-0.07,0.4615,1.0
5930,2023-12-21,KMX,CarMax Inc,1,2023-12-20,2023-12-21,78.550003,78.550003,0.051821,0.051821,0.43,0.52,0.2178,1.0
5931,2023-12-21,LMNR,Limoneira Co - Common Stock,0,2023-12-21,2023-12-22,20.510000,20.510000,0.068786,0.068786,-0.15,-0.15,0.0196,NaN
5932,2023-12-21,NKE,"Nike, Inc. Common Stock",1,2023-12-20,2023-12-21,122.529999,122.529999,0.009059,0.009059,0.85,1.03,0.2175,1.0
5933,2023-12-21,PAYX,"Paychex, Inc. - Common Stock",1,2023-12-20,2023-12-21,118.900002,118.900002,-0.070077,-0.070077,1.07,1.08,0.0056,1.0

In [27]:
merged_df

,date,symbol,security_name,premarket_pub,before_eps_date,after_eps_date,Adj Close,Close,Adj Close_pct_change,Close_pct_change,EPS Estimate,Reported EPS,Surprise(%),premarket
0,2023-01-05,CAG,"ConAgra Brands, Inc. Common Stock",1,2023-01-04,2023-01-05,39.970001,39.970001,0.034153,0.034153,0.66,0.81,0.2193,1.0
1,2023-01-05,HELE,Helen of Troy Limited - Common Stock,1,2023-01-04,2023-01-05,110.970001,110.970001,-0.014301,-0.014301,2.61,2.75,0.0551,1.0
2,2023-01-05,LNN,Lindsay Corporation Common Stock,1,2023-01-04,2023-01-05,161.860001,161.860001,0.033325,0.033325,1.18,1.65,0.3983,1.0
3,2023-01-05,LW,"Lamb Weston Holdings, Inc. Common Stock",1,2023-01-04,2023-01-05,96.029999,96.029999,0.097737,0.097737,0.74,1.28,0.7231,1.0
4,2023-01-05,MSM,"MSC Industrial Direct Company, Inc. Common Stock",1,2023-01-04,2023-01-05,77.029999,77.029999,-0.054847,-0.054847,1.46,1.48,0.0126,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5929,2023-12-21,CCL,Carnival Corporation Common Stock,1,2023-12-20,2023-12-21,19.190001,19.190001,0.061981,0.061981,-0.13,-0.07,0.4615,1.0
5930,2023-12-21,KMX,CarMax Inc,1,2023-12-20,2023-12-21,78.550003,78.550003,0.051821,0.051821,0.43,0.52,0.2178,1.0
5931,2023-12-21,LMNR,Limoneira Co - Common Stock,0,2023-12-21,2023-12-22,20.510000,20.510000,0.068786,0.068786,-0.15,-0.15,0.0196,NaN
5932,2023-12-21,NKE,"Nike, Inc. Common Stock",1,2023-12-20,2023-12-21,122.529999,122.529999,0.009059,0.009059,0.85,1.03,0.2175,1.0
5933,2023-12-21,PAYX,"Paychex, Inc. - Common Stock",1,2023-12-20,2023-12-21,118.900002,118.900002,-0.070077,-0.070077,1.07,1.08,0.0056,1.0

#### Surprise % QA

In [28]:
## QA: check how surprise % is calculated. It should be (reported minus estimate) divided by estimate
merged_df['suprise_calc'] = (merged_df['Reported EPS'] - merged_df['EPS Estimate']) / merged_df['EPS Estimate']
merged_df['suprise_calc'] = merged_df['suprise_calc'].round(4).copy()

In [29]:
merged_df

,date,symbol,security_name,premarket_pub,before_eps_date,after_eps_date,Adj Close,Close,Adj Close_pct_change,Close_pct_change,EPS Estimate,Reported EPS,Surprise(%),premarket,suprise_calc
0,2023-01-05,CAG,"ConAgra Brands, Inc. Common Stock",1,2023-01-04,2023-01-05,39.970001,39.970001,0.034153,0.034153,0.66,0.81,0.2193,1.0,0.2273
1,2023-01-05,HELE,Helen of Troy Limited - Common Stock,1,2023-01-04,2023-01-05,110.970001,110.970001,-0.014301,-0.014301,2.61,2.75,0.0551,1.0,0.0536
2,2023-01-05,LNN,Lindsay Corporation Common Stock,1,2023-01-04,2023-01-05,161.860001,161.860001,0.033325,0.033325,1.18,1.65,0.3983,1.0,0.3983
3,2023-01-05,LW,"Lamb Weston Holdings, Inc. Common Stock",1,2023-01-04,2023-01-05,96.029999,96.029999,0.097737,0.097737,0.74,1.28,0.7231,1.0,0.7297
4,2023-01-05,MSM,"MSC Industrial Direct Company, Inc. Common Stock",1,2023-01-04,2023-01-05,77.029999,77.029999,-0.054847,-0.054847,1.46,1.48,0.0126,1.0,0.0137
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5929,2023-12-21,CCL,Carnival Corporation Common Stock,1,2023-12-20,2023-12-21,19.190001,19.190001,0.061981,0.061981,-0.13,-0.07,0.4615,1.0,-0.4615
5930,2023-12-21,KMX,CarMax Inc,1,2023-12-20,2023-12-21,78.550003,78.550003,0.051821,0.051821,0.43,0.52,0.2178,1.0,0.2093
5931,2023-12-21,LMNR,Limoneira Co - Common Stock,0,2023-12-21,2023-12-22,20.510000,20.510000,0.068786,0.068786,-0.15,-0.15,0.0196,NaN,-0.0000
5932,2023-12-21,NKE,"Nike, Inc. Common Stock",1,2023-12-20,2023-12-21,122.529999,122.529999,0.009059,0.009059,0.85,1.03,0.2175,1.0,0.2118
5933,2023-12-21,PAYX,"Paychex, Inc. - Common Stock",1,2023-12-20,2023-12-21,118.900002,118.900002,-0.070077,-0.070077,1.07,1.08,0.0056,1.0,0.0093

### Decision: 
There is slight variation between the surprise % provided and the manually calculated surprise percentage. This will be attributed to rounding and the original values provided by yfinance will be used.

In [30]:
merged_df.drop(columns=['suprise_calc'], inplace=True)

In [31]:
merged_df

,date,symbol,security_name,premarket_pub,before_eps_date,after_eps_date,Adj Close,Close,Adj Close_pct_change,Close_pct_change,EPS Estimate,Reported EPS,Surprise(%),premarket
0,2023-01-05,CAG,"ConAgra Brands, Inc. Common Stock",1,2023-01-04,2023-01-05,39.970001,39.970001,0.034153,0.034153,0.66,0.81,0.2193,1.0
1,2023-01-05,HELE,Helen of Troy Limited - Common Stock,1,2023-01-04,2023-01-05,110.970001,110.970001,-0.014301,-0.014301,2.61,2.75,0.0551,1.0
2,2023-01-05,LNN,Lindsay Corporation Common Stock,1,2023-01-04,2023-01-05,161.860001,161.860001,0.033325,0.033325,1.18,1.65,0.3983,1.0
3,2023-01-05,LW,"Lamb Weston Holdings, Inc. Common Stock",1,2023-01-04,2023-01-05,96.029999,96.029999,0.097737,0.097737,0.74,1.28,0.7231,1.0
4,2023-01-05,MSM,"MSC Industrial Direct Company, Inc. Common Stock",1,2023-01-04,2023-01-05,77.029999,77.029999,-0.054847,-0.054847,1.46,1.48,0.0126,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5929,2023-12-21,CCL,Carnival Corporation Common Stock,1,2023-12-20,2023-12-21,19.190001,19.190001,0.061981,0.061981,-0.13,-0.07,0.4615,1.0
5930,2023-12-21,KMX,CarMax Inc,1,2023-12-20,2023-12-21,78.550003,78.550003,0.051821,0.051821,0.43,0.52,0.2178,1.0
5931,2023-12-21,LMNR,Limoneira Co - Common Stock,0,2023-12-21,2023-12-22,20.510000,20.510000,0.068786,0.068786,-0.15,-0.15,0.0196,NaN
5932,2023-12-21,NKE,"Nike, Inc. Common Stock",1,2023-12-20,2023-12-21,122.529999,122.529999,0.009059,0.009059,0.85,1.03,0.2175,1.0
5933,2023-12-21,PAYX,"Paychex, Inc. - Common Stock",1,2023-12-20,2023-12-21,118.900002,118.900002,-0.070077,-0.070077,1.07,1.08,0.0056,1.0

In [32]:
# export merged df with complete data to csv
merged_df.to_csv("data/exports/data_full.csv", index = False)